### PR TITLE
Better logging

### PR DESCRIPTION
**Pull request by truongio**

### CODE REVIEW

**Comment by rockerfinance** [comment]
```
panic: command "kubectl neat --help" failed with error: exit status 1
```

will instead print
```
panic: command "kubectl neat --help" failed with error: exit status 1 - output: error: unknown command "neat" for "kubectl"
```

**Review by GiGurra — CHANGES_REQUESTED** [review]
Unfortunately I don't think we can do it for the outputbytes, because that modifies the contents which should only pick up stdout of the response in the happy path (apps may print stderr for info, which arent included in the happy logical response).

This old stuff is such a hack :D.

basically, you want the combined in the panic call, but the regular output otherwise

**Comment by GiGurra** [comment]
ah wait, I was mixing it up with my other cmd line lib I wrote, which isnt used here... 

The correct way to handle this is a bit different..

**Comment by rockerfinance** [comment]
Context for this PR is that we are getting an error when trying to take a kdump (has not worked since June last year 😂 ) but we don't get a good enough error message due to the way exec.Command returns errors. Others have had the same issue: https://stackoverflow.com/questions/18159704/how-to-debug-exit-status-1-error-when-running-exec-command-in-golang

**Comment by GiGurra** [comment]
I have pushed a different solution solving the same issue (+ bumping dependencies).
So closing this PR as it is fixed.

Thanks for the input!

Fixed version published is `v1.26.26`

The full output is now this:

```
go run .
2024/02/12 21:16:53 Checking that kubectl is installed...
2024/02/12 21:16:53 Checking that kubectl neat is installed...
panic: command "kubectl neat --help" failed with error code 1: error: unknown command "neat" for "kubectl"

Did you mean this?
        set
        get


goroutine 1 [running]:
github.com/gigurra/kdump/internal/k8s.RunCommand({0x6075a6, 0x7}, {0xc0000a0400, 0x2, 0x2})
        /home/johan/git/kdump/internal/k8s/kubectl.go:111 +0x325
github.com/gigurra/kdump/internal/k8s.init.0()
        /home/johan/git/kdump/internal/k8s/kubectl.go:30 +0x112
exit status 2
```

**Pull request closed without merging**
